import ExcelJS from 'exceljs'
import { toCsv } from '../lib/csv.js'

const STATUS_LABELS = { issued: 'Issued', overdue: 'Overdue', returned: 'Returned' }
export const statusLabel = (t) => (t.status === 'returned' && t.daysOverdue > 0 ? 'Returned late' : STATUS_LABELS[t.status])



export function formatStamp(value, timeZone) {
  if (!value) return ''
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    hourCycle: 'h23',
  }).format(new Date(value))
  return parts.replace(',', '')
}

export const todayIn = (timeZone) => new Intl.DateTimeFormat('en-CA', { timeZone }).format(new Date())

const columns = (timeZone) => [
  { header: 'Book Title', width: 34, value: (t) => t.book.title },
  { header: 'Author', width: 24, value: (t) => t.book.author },
  { header: 'Book ID', width: 16, value: (t) => t.book.code },
  { header: 'Issued To (User ID)', width: 20, value: (t) => t.borrower.id },
  { header: 'Issued To (Name)', width: 24, value: (t) => t.borrower.name },
  { header: 'Issue Timestamp', width: 18, value: (t) => formatStamp(t.issuedAt, timeZone) },
  { header: 'Due Date', width: 18, value: (t) => formatStamp(t.dueAt, timeZone) },
  { header: 'Return Timestamp', width: 18, value: (t) => formatStamp(t.returnedAt, timeZone) },
  { header: 'Current Status', width: 15, value: statusLabel },
  { header: 'Days Overdue', width: 13, value: (t) => t.daysOverdue },
]


export const transactionsCsv = (rows, timeZone) => String.fromCharCode(0xfeff) + toCsv(columns(timeZone), rows)

const describeFilters = (filters) =>
  Object.entries(filters)
    .filter(([, value]) => value !== undefined && value !== 'all')
    .map(([key, value]) => `${key}: ${value}`)
    .join(', ') || 'none (full history)'

export async function transactionsXlsx(rows, { timeZone, generatedBy, filters }) {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Shelfmark'
  workbook.created = new Date()

  const cols = columns(timeZone)
  const sheet = workbook.addWorksheet('Transactions', { views: [{ state: 'frozen', ySplit: 1 }] })
  sheet.columns = cols.map(({ header, width }) => ({ header, width }))
  for (const t of rows) {
    const row = sheet.addRow(cols.map((col) => col.value(t)))
    if (t.status === 'overdue') row.font = { color: { argb: 'FFB42318' } }
  }
  const header = sheet.getRow(1)
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } }
  header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F3D2B' } }
  sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: cols.length } }

  const count = (predicate) => rows.filter(predicate).length
  const summary = workbook.addWorksheet('Summary')
  summary.columns = [{ width: 26 }, { width: 48 }]
  summary.addRows([
    ['Report', 'Issue / return history'],
    ['Generated', `${formatStamp(new Date(), timeZone)} (${timeZone})`],
    ['Generated by', generatedBy],
    ['Filters', describeFilters(filters)],
    [],
    ['Transactions in report', rows.length],
    ['Currently issued', count((t) => t.status === 'issued')],
    ['Overdue', count((t) => t.status === 'overdue')],
    ['Returned', count((t) => t.status === 'returned')],
    ['Returned late', count((t) => t.status === 'returned' && t.daysOverdue > 0)],
    ['Fines accrued (Rs)', rows.reduce((sum, t) => sum + t.fine, 0)],
  ])
  summary.getColumn(1).font = { bold: true }

  return Buffer.from(await workbook.xlsx.writeBuffer())
}
